export {AccountDevice} from 'model/account-device';
export {Account} from 'model/account';
export {AddressComponent} from 'model/address-component';
export {Address} from 'model/address';
export {Assignment} from 'model/assignment';
export {BeaconEnvironment} from 'model/beacon-environment';
export {Contact} from 'model/contact';
export {Geometry} from 'model/geometry';
export {Location} from 'model/location';
export {MerchantDetails} from 'model/merchant-details';
export {Merchant} from 'model/merchant';
export {News} from 'model/news';
export {Notification} from 'model/notification';
export {OpenHours, Date} from 'model/open-hours';
export {PublicMerchant} from 'model/public-merchant';
export {Store} from 'model/store';
export {Transaction} from 'model/transaction';